--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LegendOfMCPE/WorldEditArt
projects:
  WorldEditArt-Epsilon:
    path: WorldEditArt/
    icon: plugin_icon.png

    libs:
      - src: BlockHorizons/libgeom/libgeom
        version: "^2.0"
      - src: Falkirks/spoondetector/spoondetector
        version: "^0.0"
      - src: SOF3/pschemlib/pschemlib
        version: "^0.0"
      - src: SOF3/toomuchbuffer/toomuchbuffer
        version: "^1.0"
...
