language: php
php: ["7.0"]
sudo: false
install:
- echo "Running test on $0"
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
- cd ..
- mkdir pm
- cd pm
- wget -q -O PocketMine-MP.phar http://pmt.mcpe.me/pmb/dl.php?branch=master
- mkdir plugins
- wget -O plugins/PluginChecker.php https://gist.githubusercontent.com/PEMapModder/af032e15cde357fd378dff7ca3897782/raw/50b97c36d473284f59842ee9d9192811d6b8cebf/PluginChecker.php

before_script:
- cd $TRAVIS_BUILD_DIR
- php compile.php --travis
- cp compile/WorldEditArt_Travis.phar ../pm/plugins

script:
- cd $TRAVIS_BUILD_DIR && chmod +x lint.sh && ./lint.sh && cd ../pm
- "(echo say With XML; echo stop; echo) | php PocketMine-MP.phar --no-wizard --debug.level=2 --disable-readline
--worldeditart.debug --pluginchecker.target=WorldEditArt | tee stdout.log; grep 'PluginCheck passed' < stdout.log"
- "(echo say Without XML; echo stop; echo) | php PocketMine-MP.phar --no-wizard --debug.level=2 --disable-readline
--worldeditart.debug --worldeditart.noxml --pluginchecker.target=WorldEditArt | tee stdout.log; grep 'PluginCheck passed' < stdout.log"

after_script:
- curl -T plugins/WorldEditArt_Travis.phar https://transfer.sh/WorldEditArt-Travis.phar
