language: php
php: ["7.0"]
sudo: false
dist: trusty

install:
- "wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true"

script:
- "[ -f unstaged/WorldEditArt-Epsilon.phar] && wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - WorldEditArt-Epsilon WorldEditArt-Epsilon"
