language: php
php: ["7.0"]
sudo: false
install:
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
- cd ..
- mkdir pm
- cd pm
- wget -q -O PocketMine-MP.phar http://pmt.mcpe.me/pmb/dl.php?branch=master
- mkdir plugins

before_script:
- cd $TRAVIS_BUILD_DIR
- php compile.php
- cp compile/WorldEditArt_Dev.phar ../pm/plugins
- wget -O ../pm/plugins/ServerKiller.php https://gist.githubusercontent.com/PEMapModder/48098c1348f3c38b97e9/raw/50994e0318c0083b3cd1ba565be041c30052b1d3/ServerKiller.php

script:
- cd $TRAVIS_BUILD_DIR
- chmod +x lint.sh && ./lint.sh
- cd ../pm
- php PocketMine-MP.phar --no-wizard --debug.level=2 --disable-readline
