language: php
php: ["7.0"]
sudo: false
install:
- echo | pecl install yaml
- echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cd ..
- mkdir pm
- cd pm
- wget -q -O - https://bintray.com/artifact/download/pocketmine/PocketMine/PHP_7.0.3_x86-64_Linux.tar.gz | tar -xz
- wget -q -O PocketMine-MP.phar http://pmt.mcpe.me/pmb/dl.php?branch=master
- wget -q -O start.sh https://raw.githubusercontent.com/PocketMine/PocketMine-MP/master/start.sh
- chmod +x start.sh
- sed "s/^zend_extension=.*opcache.so/zend_extension=$(find $(pwd) -name opcache.so | sed 's/\//\\\//g')/g" bin/php7/bin/php.ini | tee bin/php7/bin/php.ini
- mkdir plugins

before_script:
- cd $TRAVIS_BUILD_DIR
- ../pm/bin/php7/bin/php compile.php
- cp compile/WorldEditArt_Dev.phar ../pm/plugins

script:
- cd ../pm
- ./start.sh
