---
name: WorldEditArt
author: PEMapModder
version: 2.0.0_gamma_dev_#0
api:
- 1.13.0
load: POSTWORLD
main: pemapmodder\worldeditart\WorldEditArt
description: A powerful advanced world editor
website: https://github.com/PEMapModder/Small-ZC-Plugins/tree/master/WorldEditArt
...
