---

#	WorldEditArt
#
#	Copyright (C) 2016 LegendsOfMCPE
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU Lesser General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	@author LegendsOfMCPE Team

Session:
  # The number of minutes that player sessions can linger for.
  # If the same player joins again with the same (case-insensitive) name
  #     and the server didnt' restart, the session will be recovered.
  # Recovering a session keeps per-session stuff like selections reusable.
  Linger: 10
...
