---
### WORLDEDITART GAMMA CONFIG FILE ###
# please do NOT delete the line above, or WorldEditArt will overwrite this file!
# DEFAULT settings for each user. A user CAN change these through commands restricted by permission nodes.
# For unspecified damage values and infinite maximum integers, put -1

defaultConfig:
  # the item to be used as a wand
  wand:
    id: 294
    damage: -1
  # the item to enable jump
  jump:
    id: 345
    damage: -1

  # options related to safety (avoid accidental destruction)
  safety:
    # when safe mode is enabled, only areas tagged as "under construction" can be edited.
    safeMode: false
    # when set to true, users have to run the //sudo command to enable WorldEditArt commands.
    sudoRequired: true
    # number of seconds each sudo session should last for
    # this value can be specified in //sudo to change.
    defaultSudoSession: -1

  # options related to optimization (reduce RAM usage, reduce lag, etc.)
  optimization:
    # the maximum number of action entries undo-able
    maxUndoQueue: 5
    # the maximum number of blocks to update per tick for this user
    tickEditThreshold: -1

# safety-related options
safety:
  # options related to safe mode and Under-Construction Zones
  ucz:
    # disallow players to enter UCZ unless they have the worldeditart.admin.ucz.entry permission node
    disallowEntry: true
  sudo:
    # max number of sudoers at the same time
    maxSudoers: -1

dataProvider:
  # data provider (database) used for user configs
  userConfig:
    # type of user config data provider (UCDP)
    # available: sqlite, mysql
    type: sqlite
    options:
      # options related to SQLite UCDP
      # ignore these if you aren't using SQLite UCDP
      sqlite:
        # file to save database at, relative to the plugin's data folder
        path: users.sqlite3
      # options related to MySQL UCDP
      # ignore these if you aren't using MySQL UCDP
      mysql:
        # MySQL connection details
        connection:
          host: example.com
          user: root
          password: ""
          # schema is also known as "database".
          # You can run the MySQL query "CREATE SCHEMA schema_name" to create a schema called schema_name
          schema: wea
          port: 3306

advanced:
  objectPool:
    # create a warning when the size of OrderedObjectPool reached this value, usually caused by a memory leak
    warningSize: 10
...
