---
# DEFAULT settings for each user. A user CAN change these through commands restricted by permission nodes.
# For unspecified damage values and infinite maximum integers, put -1
defaultConfig:
  # the item to be used as a wand
  wand:
    id: 294
    damage: -1
  # the item to enable jump
  jump:
    id: 345
    damage: -1

  # options related to safety (avoid accidental destruction)
  safety:
    # when safe mode is enabled, only areas tagged as "under construction" can be edited.
    safeMode: false
    # when set to true, users have to run the //sudo command to enable WorldEditArt commands.
    sudoRequired: true
    # number of seconds each sudo session should last for
    # this value can be specified in //sudo to change.
    defaultSudoSession: -1

  # options related to optimization (reduce RAM usage, reduce lag, etc.)
  optimization:
    # the maximum number of action entries undo-able
    maxUndoQueue: 5
    # the maximum number of blocks to update per tick for this user
    tickEditThreshold: -1

# safety-related options
safety:
  # options related to safe mode and Under-Construction Zones
  ucz:
    # disallow players to enter UCZ unless they have the worldeditart.admin.ucz.entry permission node
    disallowEntry: true
  sudo:
    # max number of sudoers at the same time
    maxSudoers: -1

# this lets you customize the names, descriptions, usages and aliases of commands.
commands:
  # note: do not modify the keys like "SudoCommand" and "UnderConstructionCommand"!
  SudoCommand:
    # the "name" attribute is the main name to use, shown in /help and //help.
    # You can add more names at the "aliases" attribute.
    # note: players have to type `//sudo` to run this command; put "sudo" if you want players to type `/sudo`
    name: "/sudo"
    description: Enable sudo mode
    # note: changing this usage message doesn't modify the syntax of the command. It only changes the usage message when a user uses sudo mode incorrectly.
    usageMessage: "//sudo [number of minutes until sudo mode ends, default forever]"
    # note: sudoRequired is true by default. If sudo is required, you can delete this line.
    sudoRequired: false
    # note: if there are no aliases, you can delete this line.
    aliases: ["/s"]
  MarkUnderConstructionCommand:
    name: "/muc"
    description: Marks your current selection as under construction.
    usageMessage: "//uc"
    aliases: ["/uc"]
  UnmarkUnderConstructionCommand:
    name: "/nuc"
    description: Remove the under-construction mark for the zone you are standing at
    usageMessage: "//uuc [.anchor]"
    aliases: ["/uuc"]

dataProvider:
  # data provider (database) used for user configs
  userConfig:
    # type of user config data provider (UCDP)
    # available: sqlite, mysql
    type: sqlite
    options:
      # options related to SQLite UCDP
      # ignore these if you aren't using SQLite UCDP
      sqlite:
        # file to save database at, relative to the plugin's data folder
        path: users.sqlite3
      # options related to MySQL UCDP
      # ignore these if you aren't using MySQL UCDP
      mysql:
        # MySQL connection details
        connection:
          host: example.com
          user: root
          password: ""
          # schema is also known as "database".
          # You can run the MySQL query "CREATE SCHEMA schema_name" to create a schema called schema_name
          schema: wea
          port: 3306
        # I am aware that some hosting companies only allocate you one schema, so all tables created by WorldEditArt will start with this prefix to avoid having the same table name as other plugins
        tablePrefix: wea_

advanced:
  objectPool:
    # create a warning when the size of OrderedObjectPool reached this value
    warningSize: 10
...
